/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\public\models\WawaOffice.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/WawaOffice.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.1, -0.1, -0.1]}>
        <mesh geometry={nodes['01_block_1'].geometry} material={materials.paintingDiffA} />
        <mesh geometry={nodes['01_block_2'].geometry} material={materials.frame} />
        <mesh geometry={nodes['01_block_3'].geometry} material={materials.mat} />
        <mesh geometry={nodes['01_block_4'].geometry} material={materials.Books} />
        <mesh geometry={nodes['01_block_5'].geometry} material={materials.woodFloorDown} />
        <mesh geometry={nodes['01_block_6'].geometry} material={materials['5Bt']} />
      </group>
      <group position={[-0.1, 2.04, -2.28]}>
        <mesh geometry={nodes['02_block_1'].geometry} material={materials.paintingDiff} />
        <mesh geometry={nodes['02_block_2'].geometry} material={materials['17 brushed iron']} />
        <mesh geometry={nodes['02_block_3'].geometry} material={materials.RLogo} />
        <mesh geometry={nodes['02_block_4'].geometry} material={materials['2Bt']} />
      </group>
      <group position={[-2.28, 4.19, -2.28]} rotation={[0, 1.57, 0]}>
        <mesh geometry={nodes['03_block_1'].geometry} material={materials.matUp} />
        <mesh geometry={nodes['03_block_2'].geometry} material={materials.woodFloorUp} />
        <mesh geometry={nodes['03_block_3'].geometry} material={materials.outFrame} />
        <mesh geometry={nodes['03_block_4'].geometry} material={materials.painting} />
        <mesh geometry={nodes['03_block_5'].geometry} material={materials['4Bt']} />
        <mesh geometry={nodes['03_block_6'].geometry} material={materials.paintingDiffB} />
        <mesh geometry={nodes['03_block_7'].geometry} material={materials.mangas} />
      </group>
      <mesh geometry={nodes['02_block002'].geometry} material={materials['1Bt']} position={[-1.52, 3.11, -1.09]} />
      <mesh geometry={nodes['02_block003'].geometry} material={materials['3Bt']} position={[-1.52, 3.73, -1.09]} />
    </group>
  )
}

useGLTF.preload('/WawaOffice.glb')
